baseURL = 'https://n9e.github.io/'
languageCode = 'en'
title = '夜莺手册'
theme = "relearn"
publishDir = "docs"

[params]
  editURL = "https://github.com/n9e/n9e.github.io/tree/main/content/"
  description = "Documentation for nightingale"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  titleSeparator = "::"
  themeVariant = ""
  disableSeoHiddenPages = true

[outputs]
  home = ["HTML", "RSS", "JSON"] # add JSON to the home page to support lunr search

[markup]
  [markup.highlight]
    style = "base16-snazzy" # choose a color theme or create your own
    guessSyntax = false     # if set to true, avoid unstyled code if no language was given but mermaid code fences will not work anymore

[markup.goldmark.renderer]
  unsafe= true

[Languages]
  [Languages.en]
    title = "N9E"
    weight = 1
    languageName = "English"
    landingPageURL = "/"
    landingPageName = "<i class='fas fa-home'></i> Home"

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/didi/nightingale"
    weight = 10

#  [[Languages.en.menu.shortcuts]]
#    name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
#    identifier = "hugodoc"
#    url = "https://gohugo.io/"
#    weight = 20
